version: "3.9"

services:
  s_phpfpm:
    build:
      context: ./config/php-fpm
      dockerfile: Dockerfile
    container_name: c_phpfpm
    restart: unless-stopped
    volumes:
      - ./src/baskethub:/var/www/baskethub
      - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini

  s_baskethub_db: 
    image: mysql:8
    container_name: c_mysql
    volumes: 
      - ./data/mysql/baskethub_db:/var/lib/mysql 
    restart: always 
    ports: 
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=baskethub_db

  s_memcached:
    image: memcached:1.6-alpine
    container_name: c_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"

  s_redis:
    image: redis:latest
    container_name: c_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  s_baskethub:
    image: nginx:alpine
    container_name: c_baskethub
    volumes:
      - ./src/baskethub:/var/www/baskethub
      - ./config/nginx/baskethub.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
